
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-16T22:43:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "475a2d1513233b9508706251fb5e5bd7ef7a69eb",
 "version": "4.1.1a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
