# Terminal emulation (screen/tmux)
export TERM="xterm-256color"

# PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/manual/bin:$PATH
export PATH=$PATH:/Library/TeX/texbin
. $HOME/.bash_profile_venv
. $HOME/.demetrius_zshrc

# RUST
. $HOME/.cargo/env
export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src

# LLVM
export PATH=/usr/local/opt/llvm/bin:$PATH
# export LD_LIBRARY_PATH=/usr/local/opt/llvm/lib:$LD_LIBRARY_PATH
# export LDFLAGS="-Wl,-rpath,/usr/local/opt/llvm/lib $LDFALGS"
export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/llvm/include $LDFLAGS"
export CFLAGS="-I/usr/local/opt/llvm/include $LDFLAGS"

# Homebrew editor
export EDITOR=nvim

# # ----------------------------- Plugins ---------------------------------------
# # inspired by https://github.com/tonylambiris/dotfiles/blob/master/dot.zshrc
#
# # Install zplug if it is not already installed
# [ ! -d ~/.zplug ] && git clone https://github.com/zplug/zplug ~/.zplug
# source ~/.zplug/init.zsh
#
# # Have zplug manage zplug
# zplug 'zplug/zplug', hook-build:'zplug --self-manage'
#
# # zsh-users
# zplug "zsh-users/zsh-completions"
# zplug "zsh-users/zsh-autosuggestions"
#
# # plugins
# if [[ $OSTYPE = (darwin)* ]]; then
#     zplug "plugins/osx",      from:oh-my-zsh
#     zplug "plugins/brew",     from:oh-my-zsh, if:"which brew"
# fi
#
# zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
# zplug "plugins/git", from:oh-my-zsh
# zplug "plugins/colorize", from:oh-my-zsh
# zplug "seebi/dircolors-solarized", ignore:"*", as:plugin
# zplug "agkozak/agkozak-zsh-theme"
#
# # Docker completion
# zplug "felixr/docker-zsh-completion"
#
# zplug load

# Plugins
plugins=(
  common-aliases
  docker
  git
  # pipenv
)

# ----------------------------- Oh My Zsh ---------------------------------------
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="powerlevel9k/powerlevel9k"
source $ZSH/custom/themes/powerlevel9k.customizations

ENABLE_CORRECTION="false"

source $ZSH/oh-my-zsh.sh

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# -------------- User configuration -----------------------
# ssh
# export SSH_KEY_PATH="~/.ssh/id_ed25519"
ssh_port_forward() { ssh "-L$1:localhost:$2 -fN $3"; }

# Added by Krypton
export GPG_TTY=$(tty)

## ALIASES
alias jpn='jupyter notebook'
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias vim='nvim'
alias inkscape="/Applications/Graphics/Inkscape.app/Contents/Resources/bin/inkscape"

# export DOCKER="$HOME/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux"

fpath+=~/.zfunc

## zsh-autosuggestions
. /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
