# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Terminal emulation (screen/tmux)
export TERM="xterm-256color"

# PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/manual/bin:$PATH
export PATH=$PATH:/Library/TeX/texbin
. $HOME/.bash_profile_venv
. $HOME/.demetrius_zshrc

export CPATH="/usr/local/include"
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib

# RUST
. $HOME/.cargo/env
export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src

# LLVM
export PATH=/usr/local/opt/llvm/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/opt/llvm/lib:$LD_LIBRARY_PATH
export LDFLAGS="-Wl,-rpath,/usr/local/opt/llvm/lib $LDFALGS"
export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS"
export CFLAGS="-I/usr/local/opt/llvm/include $CFLAGS"

# Homebrew editor
export EDITOR=nvim

# # ----------------------------- Plugins ---------------------------------------
# # inspired by https://github.com/tonylambiris/dotfiles/blob/master/dot.zshrc
#
# # Install zplug if it is not already installed
# [ ! -d ~/.zplug ] && git clone https://github.com/zplug/zplug ~/.zplug
# source ~/.zplug/init.zsh
#
# # Have zplug manage zplug
# zplug 'zplug/zplug', hook-build:'zplug --self-manage'
#
# # zsh-users
# zplug "zsh-users/zsh-completions"
# zplug "zsh-users/zsh-autosuggestions"
#
# # plugins
# if [[ $OSTYPE = (darwin)* ]]; then
#     zplug "plugins/osx",      from:oh-my-zsh
#     zplug "plugins/brew",     from:oh-my-zsh, if:"which brew"
# fi
#
# zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
# zplug "plugins/git", from:oh-my-zsh
# zplug "plugins/colorize", from:oh-my-zsh
# zplug "seebi/dircolors-solarized", ignore:"*", as:plugin
# zplug "agkozak/agkozak-zsh-theme"
#
# # Docker completion
# zplug "felixr/docker-zsh-completion"
#
# zplug load

# Plugins
plugins=(
  common-aliases
  docker
  git
  # pipenv
)

# ----------------------------- Oh My Zsh ---------------------------------------
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source $ZSH/custom/themes/powerlevel9k.customizations

ENABLE_CORRECTION="false"

source $ZSH/oh-my-zsh.sh

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# -------------- User configuration -----------------------
# ssh
# export SSH_KEY_PATH="~/.ssh/id_ed25519"
ssh_port_forward() { ssh "-L$1:localhost:$2 -fN $3"; }

# Added by Krypton
export GPG_TTY=$(tty)

## ALIASES
alias jpn='jupyter notebook'
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias vim='nvim'
alias inkscape="/Applications/Graphics/Inkscape.app/Contents/Resources/bin/inkscape"
# setting to "--experimental-remote-ip=remote" helps mosh declare the IP to Krypton, but then fails
# to actually connect to Azure...
# alias mosh="mosh --experimental-remote-ip=proxy"
# export DOCKER="$HOME/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux"
#alias pre-commit='filtered_pre_commit'
function filtered_pre_commit {
    pre-commit "$@" | grep -v Skipped
}

fpath+=~/.zfunc

## zsh-autosuggestions
. /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
